version: 2.1

jobs:
  build:
    machine:
      image: default
    steps:
      - checkout

      # Build the Docker image using your Dockerfile.
      - run:
          name: Build Docker image
          command: |
            docker build -t my-app:latest .

      # Start the container in detached mode.
      - run:
          name: Start Docker container
          command: |
            docker run -d --rm -p 8080:8080 --name my-app-instance my-app:latest

      # Wait a few seconds to allow the container to start.
      - run:
          name: Wait for container startup
          command: sleep 5

      # Test that the home page returns content containing "Express".
      - run:
          name: Test home endpoint
          command: |
            RESPONSE=$(curl -s http://localhost:8080/)
            echo "Response: $RESPONSE"
            # Check if the response contains "BackSpace" (adjust as needed)
            echo "$RESPONSE" | grep -q "BackSpace" || {
              echo "Test failed: 'BackSpace' not found in response"
              docker logs my-app-instance
              exit 1
            }

      # Stop the container after testing.
      - run:
          name: Stop Docker container
          command: docker stop my-app-instance

      - run:
          name: Docker Hub Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build the Docker image with a tag that includes the commit SHA.
      - run:
          name: Docker images list
          command: |
            docker images

      # Push the Docker image to Docker Hub.
      - run:
          name: Push Docker image
          command: |
            docker push $DOCKER_USERNAME/my-app:$CIRCLE_SHA1

workflows:
  build_test_and_push:
    jobs:
      - build
