version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Use a basic image with Docker CLI installed.
    steps:
      - checkout

      # Enable Docker layer caching by setting up remote Docker.
      - setup_remote_docker:
          version: 20.10.7

      # Build the Docker image from your Dockerfile.
      - run:
          name: Build Docker image
          command: |
            docker build -t my-app:latest .

      # Run the container in detached mode.
      - run:
          name: Start Docker container
          command: |
            docker run -d --rm -p 8080:8080 --name my-app-instance my-app:latest

      # Wait a few seconds to ensure the container is up and running.
      - run:
          name: Wait for container startup
          command: sleep 5

      # Test that the application is responding on the expected route.
      # Replace 'http://localhost:8080/your_route' with your endpoint and
      # 'expected_output' with the response you expect.
      - run:
          name: Test container endpoint
          command: |
            RESPONSE=$(curl -s http://localhost:8080/your_route)
            echo "Response: $RESPONSE"
            if [ "$RESPONSE" != "expected_output" ]; then
              echo "Test failed: Expected 'expected_output' but got '$RESPONSE'"
              docker logs my-app-instance
              exit 1
            fi

      # Stop the container after testing.
      - run:
          name: Stop Docker container
          command: docker stop my-app-instance

  push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      # Set up Docker in Docker.
      - setup_remote_docker:
          version: 20.10.7

      # Log in to Docker Hub using the environment variables.
      - run:
          name: Docker Hub Login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      # Build the image with a tag that includes the commit SHA.
      - run:
          name: Build Docker image for push
          command: |
            docker build -t "$DOCKERHUB_USER/my-app:$CIRCLE_SHA1" .

      # Push the image to Docker Hub.
      - run:
          name: Push Docker image
          command: |
            docker push "$DOCKERHUB_USER/my-app:$CIRCLE_SHA1"

workflows:
  build_test_and_push:
    jobs:
      - build
      - push:
          # The push job only runs if the build job succeeds.
          requires:
            - build
