version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # or any other base image you need
    working_directory: ~/repo

jobs:
  setup:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Update apt-get and install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo systemctl status docker
            sudo usermod -aG docker $USER
            newgrp docker

  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app .
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 my-app
      - run:
          name: Wait for Service to Start
          command: |
            sleep 10  # Adjust this for your application's startup time
      - run:
          name: Test Application Response
          command: |
            curl -f http://localhost:8080 || exit 1
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push my-app

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup
