version: 2.1
orbs:
  docker: circleci/docker@3.1.1

jobs:
  build-test-and-push:
    docker:
      - image: cimg/base:2024.01
    environment:
      DOCKER_IMAGE_NAME: my-app
    steps:
      - checkout
      - setup_remote_docker
      
      # Build Docker image
      - docker/build:
          image: $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME
          tag: "latest,${CIRCLE_SHA1}"
          dockerfile: Dockerfile
      
      # Test running container
      - run:
          name: Run container
          command: docker run -d --name my-app $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest
      - run:
          name: Wait for container startup
          command: sleep 5
      - run:
          name: Verify container health
          command: |
            CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my-app)
            curl -sS --retry 3 --retry-delay 5 http://$CONTAINER_IP:8080/health-check
      
      # Push to Docker Hub
      - docker/login:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - docker/push:
          image: $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME
          tag: "latest,${CIRCLE_SHA1}"

workflows:
  main:
    jobs:
      - build-test-and-push:
          context: 
            - dockerhub-creds