version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current  # Use Ubuntu 22.04 VM
    environment:
      NODE_VERSION: "16"

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout

      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Start application
          command: nohup npm start &  # Runs app in the background

      - run:
          name: Wait for Service to Start
          command: sleep 10  # Adjust if needed

      - run:
          name: Test Application Response
          command: curl -v http://localhost:8080 || exit 1

  docker-build:
    executor: machine-executor
    steps:
      - checkout
      
      - run:
          name: Install Docker CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $USER

      - run:
          name: Build Docker Image
          command: docker build -t your-dockerhub-username/node-js-sample .

      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker Image
          command: docker push your-dockerhub-username/node-js-sample

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - docker-build:
          requires:
            - build  # Only run if build succeeds
